# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.21.0"

gem "random-word-generator", "~> 0.0.1"

gem "colorize", "~> 0.8.1"

gem "tty-cursor", "~> 0.7.1"
